application: holdmypage
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /js
  static_dir: js
- url: /add
  login: required
  script: _go_app
- url: /batchadd
  login: required
  script: _go_app
- url: /edittitle
  login: required
  script: _go_app
- url: /edittags
  login: required
  script: _go_app
- url: /getlinks
  login: required
  script: _go_app
- url: /.*
  script: _go_app
